book_count/urls.py
from django.urls import path
from .views import riwayat, riwayat_data

app_name = 'book_count'

urlpatterns = [
    path('', riwayat, name='riwayat'),
    path('data', riwayat_data, name='riwayat_data'),
]

jambu_muda/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

app_name = 'jambu_muda'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cari/', views.cari, name='cari'),
    path('check/', views.checker, name="check"),
    path('pinjam/', views.pinjam, name='pinjam'),
    path('peminjaman/', views.peminjaman, name='peminjaman'),
    path('complete/', views.complete, name="complete"),
    path('tambah_buku/', views.tambah_buku, name='tambah_buku'),
    path('testimoni/', views.testimoni, name='testimoni'),
    path('auth/', include('social_django.urls', namespace='social'))
]

sijambumuda/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jambu_muda.urls')),
    path('riwayat/', include('book_count.urls')),
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jambu_muda/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Book(models.Model):
    CATEGORY_CHOICES = (
        ('science', 'Science'),
        ('scifi', 'Science Fiction'),
        ('hobby', 'Hobby'),
        ('other', 'Other'),
    )
    id_number = models.CharField(max_length=20, unique=True)
    quota = models.IntegerField()
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    synopsis = models.TextField()
    borrow = models.ManyToManyField(User, blank=True, through='BookBorrow')
    cover_base64 = models.TextField(blank=True)

    @property
    def get_borrow(self):
        return self.borrow.distinct()

    def __str__(self):
        return '[{}] {}'.format(self.id_number, self.title)


class BookBorrow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date = models.DateField()


class Testimony(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile')
    id_number = models.CharField(max_length=20, unique=True)
    address = models.TextField()


User._meta.get_field('email')._unique = True

jambu_muda/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Book, BookBorrow, UserProfile, Testimony



class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = 'Nama depan'
        self.fields['last_name'].label = 'Nama belakang'

        for fieldname in UserForm.Meta.fields:
            self.fields[fieldname].help_text = None


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('id_number', 'address')
        labels = {'id_number': 'Nomor identitas', 'address': 'Alamat'}

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['address'].widget.attrs['class'] = 'materialize-textarea'


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'autofocus': True})

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            self.user = authenticate(username=username, password=password)
            if self.user:
                self.login_allowed = True
            else:
                self.add_error('username', 'Username atau password salah.')
                self.add_error('password', 'Username atau password salah.')


class BookForm(forms.ModelForm):
    cover = forms.ImageField()

    class Meta:
        model = Book
        fields = ('id_number', 'category', 'title',
                  'author', 'publisher', 'synopsis','quota', 'cover')

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['synopsis'].widget.attrs['class'] = 'materialize-textarea'
        self.fields['id_number'].widget.attrs['autofocus'] = True
        self.fields['cover'].widget.attrs['accept'] = '.jpg,.jpeg'

class BorrowBookForm(forms.Form):
    book = forms.ModelChoiceField(
        label="Nomor Buku", queryset=Book.objects.all().exclude(quota=0))
    date = forms.DateField(
        label="Tanggal Pinjam (yyyy-mm-dd)",
        input_formats=['%Y-%m-%d'],
        widget=forms.DateTimeInput(attrs={'class': 'datepicker', }),
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(BorrowBookForm, self).__init__(*args, **kwargs)

class TestiForm(forms.ModelForm):
    class Meta:
        model = Testimony
        fields = ('comment',)
        labels = {'comment': 'Masukkan Testimoni anda'}

jambu_muda/views.py
from datetime import datetime, timedelta
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import BookForm, BorrowBookForm, LoginForm, UserForm, UserProfileForm, TestiForm
from .models import Book, BookBorrow, UserProfile, Testimony
from book_count.models import BookBorrowHistory
from django.db.models import Q


# Create your views here.

def anonymous_required(view, redirect_to='/dashboard'):
    wrapper = user_passes_test(
        lambda u: u.is_anonymous,
        login_url=redirect_to,
    )
    return wrapper(view)


def superuser_required(view, redirect_to='/'):
    wrapper = user_passes_test(
        lambda u: u.is_superuser,
        login_url=redirect_to,
    )
    return wrapper(view)


@anonymous_required
def index(request):
    testimoni = Testimony.objects.all()
    return render(request, 'jambu_muda/index.html', {'user': request.user,
                                                     'user_count': User.objects.all().count(),
                                                     'book_count': Book.objects.all().count(),
                                                     'testimoni': testimoni,
                                                     })


@anonymous_required
def signup(request):
    if request.method == 'POST':
        uform = UserForm(request.POST)
        pform = UserProfileForm(request.POST)
        if uform.is_valid() and pform.is_valid():
            user = uform.save()
            profile = pform.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('jambu_muda:login')
    else:
        uform = UserForm()
        pform = UserProfileForm()
    return render(request, 'jambu_muda/signup.html', {'uform': uform, 'pform': pform})


@anonymous_required
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            if form.login_allowed:
                auth_login(request, form.user)
                return redirect('jambu_muda:dashboard')
    else:
        form = LoginForm()

    return render(request, 'jambu_muda/login.html', {'form': form})


@login_required
def logout(request):
    auth_logout(request)
    return redirect('jambu_muda:index')


@login_required
def cari(request):
    return render(request, 'jambu_muda/cari.html', {'user': request.user, 'books': Book.objects.all()})


@login_required
def pinjam(request):
    if request.method == 'POST':
        form = BorrowBookForm(request.POST, request=request)
        if form.is_valid():
            data = {'user':request.user, 'book':form.cleaned_data['book'], 'date':form.cleaned_data['date']}
            return_date = data['date'] + timedelta(weeks=2)
            BookBorrow(**data).save()
            BookBorrowHistory(return_date=return_date, **data).save()
            bukuDiPinjam = Book.objects.get(id_number=data['book'].id_number)
            if bukuDiPinjam.quota > 0:
                bukuDiPinjam.quota -= 1
            bukuDiPinjam.save()
            return redirect('jambu_muda:dashboard')
    else:
        form = BorrowBookForm(request=request)
    return render(request, 'jambu_muda/pinjam.html', {'user': request.user, 'form': form})


@login_required
def peminjaman(request):
    BookBorrow.objects.filter(
        date__lt=datetime.today() - timedelta(weeks=2)).delete()
    return render(request, 'jambu_muda/peminjaman.html', {'user': request.user,
                                                          'books': Book.objects.filter(bookborrow__date__gte=datetime.today() - timedelta(weeks=2)).distinct()})


@login_required
def dashboard(request):
    BookBorrow.objects.filter(
        date__lt=datetime.today() - timedelta(weeks=2)).delete()
    return render(request, 'jambu_muda/dashboard.html', {'user': request.user,
                                                         'borrowed_books': request.user.bookborrow_set.filter(user=request.user, date__gte=datetime.today() - timedelta(weeks=2))})


@superuser_required
def tambah_buku(request):
    import base64

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            with form.cleaned_data['cover'].open("rb") as cover:
                cover_base64 = 'data:image/jpg;base64,{}'.format(
                    base64.b64encode(cover.read()).decode())

                book = form.save()
                book.cover_base64 = cover_base64
                book.save()
                return redirect('jambu_muda:tambah_buku')
    else:
        form = BookForm()
    return render(request, 'jambu_muda/tambah_buku.html', {'user': request.user, 'form': form})


@login_required
def checker(request):
    print("masuk checker")
    try:
        print("masuk try")
        user = UserProfile.objects.all().filter(user=request.user)
        return redirect('jambu_muda:pinjam')
    except:
        print("masuk except")
        return redirect('jambu_muda:complete')


@login_required
def complete(request):
    if request.method == 'POST':
        pform = UserProfileForm(request.POST)
        if pform.is_valid():
            profile = pform.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('jambu_muda:dashboard')
    else:
        pform = UserProfileForm()
    return render(request, 'jambu_muda/complete.html', {'pform': pform})

@login_required
def testimoni(request):
    if request.method == 'POST':
        form = TestiForm(request.POST)
        testimony = form.save(commit=False)
        testimony.user = request.user
        testimony.save()
        return redirect('jambu_muda:dashboard')
    else:
        form = TestiForm()
    return render(request, 'jambu_muda/testimoni.html', {'testimony_list': Testimony.objects.all(),'form':form})

jambu_muda/templates/jambu_muda/cari.html
{%include 'jambu_muda/navbar2.html'%}
{% load static %}
<h1 class="text-center texthijau halo">Cari Buku, Yuk</h1>

<!-- Input table -->
<h1 class="text-center texthijau halo">Peminjaman dapat dilakukan di halaman <a href="{% url 'jambu_muda:pinjam' %}">pinjam buku</a>.</h1>
<br>
<table>

  <!-- Headers -->
  <thead>
  <tr>
    <th>Cover</th>
    <th>Nomor</th>
    <th>Judul</th>
    <th>Pengarang</th>
    <th>Penerbit</th>
    <th>Kategori</th>
    <th>Stok</th>
    <th>Sinopsis</th>
  </tr>
</thead>

  <!-- Mulai for loop -->
  {% for book in books %}
  <tbody>
  <tr>
    <td><img class="cover" src="{{ book.cover_base64 }}" onerror="this.onerror=null;this.src='{% static 'assets/def_img.jpg' %}';"></td>
    <td>{{ book.id_number }}</td>
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.publisher }}</td>
    <td>{{ book.get_category_display }}</td>
    {% if book.quota == 0 %}
    <td class="empty"> Habis </td>
    {% else %}
    <td> {{book.quota}} </td>
    {% endif %}
    <td><a href="#modal{{ forloop.counter }}" class="modal-trigger"><button class="greenbut">Baca</button></a></td>

    <!-- Isi modal -->
    <div id="modal{{ forloop.counter }}" class="modal">
      <div class="modal-content">
        <!-- Isi pake judul buku -->
        <h4>{{ book.title }}</h4>
        <!-- Isi pake sinopsis buku -->
        <p>{{ book.synopsis|linebreaks }}</p>
      </div>
      <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
      </div>
    </div>
  </tr>
  <!-- End for loop -->
  {% endfor %}
</tbody>
</table>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var options = {};
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, options);
  });
</script>
</body>

jambu_muda/templates/jambu_muda/dashboard.html
{% include 'jambu_muda/navbar2.html' %}
{% load static %}

<div class="container">
  <div class="row">
    <h1 class="text-center texthijau halo">Halo, <b>{{ user.get_full_name }}</b></h1>
  </div>
  {% if borrowed_books %}
  <div class="row">
    <h1 class="text-center texthijau halo">Inilah daftar peminjamanmu.</h1>
  </div>
  {% endif %}
  <!-- Mulai For LOOP -->
  {% for borrowed_book in borrowed_books %}
  <div class="row">
      <div class="col s12 m7">
          <div class="card horizontal hoverable">
            <div class="card-image">
              <img class="cover" src="{{ borrowed_book.book.cover_base64 }}" onerror="this.onerror=null;this.src='{% static 'assets/def_img.jpg' %}';">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <p class="textkotak">Nomor Buku</p>
                <p><b>{{ borrowed_book.book.id_number }}</b></p>
                <p class="textkotak">Judul</p>
                <p><b>{{ borrowed_book.book.title }}</b></p>
                <p class="textkotak">Kategori</p>
                <p><b>{{ borrowed_book.book.get_category_display }}</b></p>
                <p class="textkotak">Penulis</p>
                <p><b>{{ borrowed_book.book.author }}</b></p>
                <p class="textkotak">Penerbit</p>
                <p><b>{{ borrowed_book.book.publisher }}</b></p>
                <p class="textkotak">Tanggal Pinjam</p>
                <p><b>{{ borrowed_book.date }}</b></p>
              </div>
            </div>
          </div>
        </div>
  </div>
  {% empty %}
  <h1 class="text-center texthijau halo">Anda sedang tidak meminjam buku.</h1>
  {% endfor %}
  <!-- END FOR LOOP -->
  <div class="container hide-on-med-and-up">
      <div class="row text-center">
        <a href="{% url 'jambu_muda:logout' %}" class="redbut">Log out</a>
      </div>
  </div>
</div>

jambu_muda/templates/jambu_muda/index.html
{% include 'jambu_muda/navbar.html' %}
{% load static %}
  <!-- Main Body -->
  <div class="overlay center">
      <div class="preloader-wrapper big active">
          <div class="spinner-layer spinner-green-only">
            <div class="circle-clipper left">
              <div class="circle"></div>
            </div><div class="gap-patch">
              <div class="circle"></div>
            </div><div class="circle-clipper right">
              <div class="circle"></div>
            </div>
          </div>
        </div>
  </div>
  
  <img class="gambar1 responsive-img" src="{% static 'assets/1.png' %}" alt="" id="asset1" />
  <div class="container" id="awal">
    <div class="row">
      <div class="col s12 m12 l8 tgline">
        <h1 class="judul">Meminjam buku</h1>
        <h1 class="judul">senikmat <span class="texthijau">jambu</span>.</h1>
      </div>
      <div class="col s12 m12 l6">
      </div>
      <div class="col s12 m12 l6">
          <h1 style="font-size:1em;">
            Sekarang meminjam buku hanya memerlukan satu menit.
          </h1>
          <a href="{% url 'jambu_muda:signup' %}"><button class="greenbut">Pinjam</button></a>
          <a href="{% url 'jambu_muda:login' %}"><button class="greenbut_alt">Masuk</button></a>
        </div>
    </div>
  </div>


  <img class="gambar1" src="{% static 'assets/2.png' %}" alt="" id="asset2" />

  <div class="container" id="tentang">
    <div class="row">
      <div class="col s12 m12 l6 tgline">
        <h1 class="judul">Tentang kami</h1>
        <p class="sub2">
          sijambu muda adalah sebuah platform peminjaman buku yang dibuat
          untuk memudahkan peminjam buku meminjam dan melacak pinjamannya.
        </p>
        <p class="motto">daftar. pinjam. baca.</p>
      </div>
    </div>
  </div>

  <div class="container" id="stats">
    <div class="row">
      <div class="col s12 m12 l12">
        <h1 class="judul">Stats</h1>
        <p class="sub2">Saat ini kami telah memiliki:</p>
      </div>
    </div>
    <div class="row">
      <div class="col s12 m6 l3">
        <div class="kotak">
          <p>{{ book_count }}<br>buku</p>
        </div>
      </div>
      <div class="col s12 m12 l3">
        <div class="kotak">
          <p>{{ user_count }}<br>pengguna</p>
        </div>
      </div>
      <div class="col s12 m12 l3">
        <p class="sub2">.. dan ini baru permulaan.</p>
      </div>
    </div>
  </div>

  <section class="bg-green" id="faq">
    <div class="container" style="padding-bottom: 1em;">
      <h1 class="faq">FAQ</h1>
      <p style="color: white; font-size:1.2em; margin:0;" class="subtitle">
        Bagaimana cara meminjam di sijambu muda?
      </p>
      <p class="subtitle" style="font-size: 1.2em; font-weight:
    300; color: white; margin: 0; margin-bottom: 1em;">
        Daftarkan diri anda, pilih buku yang anda ingin pinjam, lalu pinjam.
        Begitu mudah.
      </p>
      <p style="color: white; font-size:1.2em; margin:0; " class="subtitle">
        Apakah ada batas peminjaman di sijambu muda?
      </p>
      <p class="subtitle" style="font-size: 1.2em; font-weight:
    300; color: white; margin: 0; margin-bottom: 1em;">
        Batas peminjaman anda adalah 2 minggu.
      </p>
      <p style="color: white; font-size:1.2em; margin:0; " class="subtitle">
        Apakah ada batasan umur untuk meminjam?
      </p>
      <p class="subtitle" style="font-size: 1.2em; font-weight:
    300; color: white; margin: 0; margin-bottom: 1em;">
        Tidak, selama anda terdaftar di instansi akademik (sekolah atau
        universitas).
      </p>
      <p style="color: white; font-size:1.2em; margin:0; " class="subtitle">
        Apa yang terjadi bila saya terlambat mengembalikan?
      </p>
      <p class="subtitle" style="font-size: 1.2em; font-weight:
    300; color: white; margin: 0; margin-bottom: 1em;">
        Anda dikenakan denda Rp 1000 per hari.
      </p>
      <p style="color: white; font-size:1.2em; margin:0; " class="subtitle">
        Website nya keren banget, siapa yang bikin?
      </p>
      <p class="subtitle" style="font-size: 1.2em; font-weight:
    300; color: white; margin: 0; margin-bottom: 1em;">
        Makasih~ Lihat contributor <a href="https://gitlab.com/ppw-sans/sijambumuda" >disini</a>.
      </p>
    </div>
  </section>
<!-- Testimony -->
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12 text-center">
        <h1 class="subtitle text-center">
          Testimoni
        </h1>
      </div>
    </div>
    <div class="row">
      <div class="col s12 m12 l12 text-center">
        <div id="carousel">
          {% for testi in testimoni %}
          <div class="kartu-testi">
            <h5>{{testi.comment}}</h5>
            <p><b>{{testi.user.get_full_name}}</b></p>
          </div>
          {% endfor %}
        </div>
        <a href="{% url 'jambu_muda:login' %}"><button class="greenbut">Login untuk memberikan testimoni</button></a>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12 text-center">
        <h1 class="subtitle text-center">
          “There is no friend as loyal as a book.”
        </h1>
        <h1 class="subtitle text-center ernes">-Ernest Hemingway</h1>
        <a href="{% url 'jambu_muda:signup' %}"><button class="greenbut">Pinjam</button></a>
      </div>
    </div>
  </div>
  <script
  src="https://code.jquery.com/jquery-3.4.0.js"
  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css">
  <script src="{% static 'js/carousel.js' %}"></script>
</body>

</html>

<!-- 

██╗██████╗  ██████╗ ███╗   ██╗███╗   ███╗ █████╗ ███╗   ██╗                     
██║██╔══██╗██╔═══██╗████╗  ██║████╗ ████║██╔══██╗████╗  ██║                     
██║██████╔╝██║   ██║██╔██╗ ██║██╔████╔██║███████║██╔██╗ ██║                     
██║██╔══██╗██║   ██║██║╚██╗██║██║╚██╔╝██║██╔══██║██║╚██╗██║                     
██║██║  ██║╚██████╔╝██║ ╚████║██║ ╚═╝ ██║██║  ██║██║ ╚████║                     
╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝                     
                                                                                
 █████╗ ███╗   ██╗██████╗                                                       
██╔══██╗████╗  ██║██╔══██╗                                                      
███████║██╔██╗ ██║██║  ██║                                                      
██╔══██║██║╚██╗██║██║  ██║                                                      
██║  ██║██║ ╚████║██████╔╝                                                      
╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝                                                       
                                                                                
██████╗ ██╗      █████╗  ██████╗██╗  ██╗██╗    ██╗██╗██████╗  ██████╗ ██╗    ██╗
██╔══██╗██║     ██╔══██╗██╔════╝██║ ██╔╝██║    ██║██║██╔══██╗██╔═══██╗██║    ██║
██████╔╝██║     ███████║██║     █████╔╝ ██║ █╗ ██║██║██║  ██║██║   ██║██║ █╗ ██║
██╔══██╗██║     ██╔══██║██║     ██╔═██╗ ██║███╗██║██║██║  ██║██║   ██║██║███╗██║
██████╔╝███████╗██║  ██║╚██████╗██║  ██╗╚███╔███╔╝██║██████╔╝╚██████╔╝╚███╔███╔╝
╚═════╝ ╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝╚═════╝  ╚═════╝  ╚══╝╚══╝ 
                                                                                
██████╗ ██╗███████╗██████╗                                                      
██╔══██╗██║██╔════╝██╔══██╗                                                     
██║  ██║██║█████╗  ██║  ██║                                                     
██║  ██║██║██╔══╝  ██║  ██║                                                     
██████╔╝██║███████╗██████╔╝                                                     
╚═════╝ ╚═╝╚══════╝╚═════╝                                                      
                                                                                




 -->

jambu_muda/templates/jambu_muda/navbar2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <title>Situs pinjam buku | Sijambumuda</title>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!-- Materialize -->
    <!-- Compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />

    <!-- Poppins font -->
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:300,400i,500,600,700"
      rel="stylesheet"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        var options = {
          format: "yyyy-mm-dd",
          defaultDate: new Date(),
          minDate: new Date(),
          setDefaultDate: true
        };
        var elems = document.querySelector(".datepicker");
        var instance = M.Datepicker.init(elems, options);
      });
      document.addEventListener("DOMContentLoaded", function() {
        var options = {};
        var elems = document.querySelectorAll("select");
        var instances = M.FormSelect.init(elems, options);
      });
    </script>
    <script src="{% static "js/carousel.js" %}"></script>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav class="navhello">
        <div class="nav-wrapper white">
          <a
            href="{% url 'jambu_muda:dashboard' %}"
            class="brandz"
            style="color:black;"
            >sijambu muda</a
          >\
          <a href="{% url 'jambu_muda:cari' %}" class="brand-menu">Cari</a>
          <a href="{% url 'jambu_muda:pinjam' %}" class="brand-menu">Pinjam</a>
          <a href="{% url 'jambu_muda:peminjaman' %}" class="brand-menu"
            >Peminjaman</a
          >
          <a href="{% url 'book_count:riwayat' %}" class="brand-menu">Riwayat</a>
          <a href="{% url 'jambu_muda:testimoni' %}" class="brand-menu">Testimoni</a>
          {% if user.is_superuser %}
          <a href="{% url 'jambu_muda:tambah_buku' %}" class="brand-menu"
            >Tambah Buku</a
          >
          {% endif %}
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
              <a href="#" class="brand-menu2">Hello, {{ user.first_name }}</a>
            </li>
            <li>
              <a href="{% url 'jambu_muda:logout' %}"
                ><button class="redbut">Log out</button></a
              >
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </body>
</html>

jambu_muda/templates/jambu_muda/pinjam.html
{% include 'jambu_muda/navbar2.html' %}


<h1 class="text-center texthijau halo">Pinjam Buku, Yuk</h1>
<!-- Isi forms disini -->

<!-- Masukin form disini -->
<div class="container">
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% include 'jambu_muda/form_template.html' with form=form %}
        <button type="submit" class="greenbut text-center">Pinjam Buku</button>
    </form>

</div>