book_count/urls.py
from django.urls import path
from .views import riwayat, riwayat_data

app_name = 'book_count'

urlpatterns = [
    path('', riwayat, name='riwayat'),
    path('data', riwayat_data, name='riwayat_data'),
]

jambu_muda/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

app_name = 'jambu_muda'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cari/', views.cari, name='cari'),
    path('check/', views.checker, name="check"),
    path('pinjam/', views.pinjam, name='pinjam'),
    path('peminjaman/', views.peminjaman, name='peminjaman'),
    path('complete/', views.complete, name="complete"),
    path('tambah_buku/', views.tambah_buku, name='tambah_buku'),
    path('testimoni/', views.testimoni, name='testimoni'),
    path('auth/', include('social_django.urls', namespace='social'))
]

sijambumuda/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jambu_muda.urls')),
    path('riwayat/', include('book_count.urls')),
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_count/models.py
from django.db import models
from django.contrib.auth.models import User
from jambu_muda.models import Book

# Create your models here.

class BookBorrowHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date = models.DateField()
    return_date = models.DateField()

book_count/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from .models import BookBorrowHistory
from datetime import timedelta
import json

# Create your views here.

@login_required
def riwayat(request):
    return render(request,'book_count/riwayat.html', {'user': request.user})

@login_required
def riwayat_data(request):
    if request.is_ajax():
        borrowed_books = request.user.bookborrowhistory_set.filter(user=request.user).order_by('-date')
        print(len(borrowed_books))
        data = dict()

        for idx, borrowed_book in enumerate(borrowed_books):
            data[idx] = {
                'id': borrowed_book.book.id_number,
                'cover': borrowed_book.book.cover_base64,
                'title': borrowed_book.book.title,
                'category': borrowed_book.book.get_category_display(),
                'author': borrowed_book.book.author,
                'publisher': borrowed_book.book.publisher,
                'date': str(borrowed_book.date),
                'return_date': str(borrowed_book.date + timedelta(weeks=2)),
            }

        data = json.dumps(data)
        return JsonResponse(data, safe=False)

book_count/templates/book_count/riwayat.html
{% include 'jambu_muda/navbar2.html' %}
{% load static %}

<div class="container">
    <div id="riwayat">
    </div>

    <div class="container hide-on-med-and-up">
        <div class="row text-center">
            <a href="{% url 'jambu_muda:logout' %}" class="redbut">Log out</a>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
    $(document).ready(function () {
        $.ajax({
            url: "{% url 'book_count:riwayat_data' %}",
            dataType: 'json',
            success: function (data) {
                obj = $.parseJSON(data);
                obj_length = Object.keys(obj).length;
                query = '';

                if(obj_length > 0){
                    info = `
                        <div class="row">
                            <h1 class="text-center texthijau halo">Riwayat Peminjaman Anda</h1>
                            <h1 class="text-center texthijau halo">( ` + obj_length + ` buku )</h>
                        </div>
                    `;
                } else {
                    info = `
                    <h1 class="text-center texthijau halo">Anda belum pernah meminjam buku.</h1>
                    `;
                }

                $.each(obj, function(i, item){
                    query += `
                    <div class="row">
                        <div class="col s12 m7">
                            <div class="card horizontal hoverable">
                                <div class="card-image">
                                    <img class="cover" src="` + item.cover + `"
                                        onerror="this.onerror=null;this.src='{% static 'assets/def_img.jpg' %}';">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p class="textkotak">Nomor Buku</p>
                                        <p><b>` + item.id + `</b></p>
                                        <p class="textkotak">Judul</p>
                                        <p><b>` + item.title + `</b></p>
                                        <p class="textkotak">Kategori</p>
                                        <p><b>` + item.category + `</b></p>
                                        <p class="textkotak">Penulis</p>
                                        <p><b>` + item.author + `</b></p>
                                        <p class="textkotak">Penerbit</p>
                                        <p><b>` + item.publisher + `</b></p>
                                        <p class="textkotak">Tanggal Pinjam</p>
                                        <p><b>` + item.date + `</b></p>
                                        <p class="textkotak">Tanggal Kembali</p>
                                        <p><b>` + item.return_date + `</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    `;
                });

                $('#riwayat').append(info);
                $('#riwayat').append(query);
            }
        });
    });
</script>